#### PyPi Package : NumPy

In [1]:
# pip install numpy
import numpy as np

In [5]:
# Given lists
list1 = [1, 2, 3]
list2 = [1, 2, 3]
print(list1+list2)


# # Initialize an empty list to store the results
result = []

# Loop through the lists using the index
for i in range(len(list1)):
    # Add corresponding elements and append to the result list
    sum_value = list1[i] + list2[i]
    result.append(sum_value)

# Print the result
print(result)

print(np.array(list1)+np.array(list2))


[1, 2, 3, 1, 2, 3]
[2, 4, 6]
[2 4 6]


# Linear Algebra

In [7]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print("")
print(np.matmul(a, b))



[[19 22]
 [43 50]]


# Statistics

In [23]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.max(stats))
print(np.sum(stats))
print(np.sum(stats, axis=0))
print("Mean",np.mean(stats))
print((1+2+3+4+5+6)/6)

stats1 = np.array([[5, 4, 3], [2, 1, 6]])
print("median",np.median(stats1))
stats2 = np.array([[5, 4, 3], [2, 1, 6]])
print("Median for each row",np.median(stats2, axis=1))
stats3 = np.array([2,3,4,5,6,1,7])
print("Median from odd number",np.median(stats3))
stats4 = np.array([2,3,4,5,6,1,7,8])
print("Median from even number",np.median(stats4))


1
[3 6]
6
21
[5 7 9]
Mean 3.5
3.5
median 3.5
Median for each row [4. 2.]
Median from odd number 4.0
Median from even number 4.5


# Reorganizing Arrays